version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
     - run: docker build -t chaospott/documents .
     - run: |
         docker tag chaospott/documents chaospott/documentsmarc:$CIRCLE_SHA1
         docker push chaospott/documents:$CIRCLE_SHA1
         docker push chaospott/documents:latest